### ISSUE TITLE
alltxt

### ISSUE THREAD

**Issue by shaobeipan** [zwingser/proxy_pool#1]
你好

 我按照你的gettxt 修改添加了alltxt
@app.route('/alltxt/')
def alltxt():
    https = request.args.get("type", "").lower() == 'https'
    proxy = proxy_handler.getall(https)
    return proxy._proxy if proxy else {"code": 0, "src": "no proxy"}

提示内部错误.

**Comment by zwingser** [comment]
不能照抄gettxt的代码,all是个集合,要改成txt需要自己做个循环处理.
